### ISSUE TITLE
Create a Pulumi stack for NorthWykeTwin

### ISSUE THREAD

**Issue by mhauru** [alan-turing-institute/NorthWykeTwin#1]
Can use the same Pulumi backend storage and key vault (but different key) as our test stack.

**Comment by GiorgioCerro** [comment]
When running` pulumi up` I get this:
error: Missing required configuration variable 'dtbase-azure:sql-server-[secret]'
please set a value using the command `pulumi config set dtbase-azure:sql-server-[secret] <value>`

**Comment by GiorgioCerro** [comment]
NorthWykeTwin stack created on Azure. 
Docker containers created and both the frontend and the backend work beautifully.
